services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      DB_PATH: /backend/data/db1.db
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - ./data:/backend/data
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
